language: php
php:
 - 5.3

sudo: false

notifications:
  email:
    secure: TNv7WYCJ1ei3wgoXtNM+/Je4ZU7fgcUSsAUQnjC8h2MIE0ImwxPC2xt5t6BR8Mi6XrPCBQ1aRjAvhSFGdYcfhWDJwU0Nq6BfynVwE4OR5/KNhZ9TvMlCQ+eRQD8qJLNqe2MWxMZcdlbrk0rNEhTDcPn3b6dz9Zuji4woe5wksxA=

env:
 - DB=MYSQL CORE_RELEASE=3.4
 - DB=PGSQL CORE_RELEASE=3.4
 - DB=SQLITE3 CORE_RELEASE=3.4
 - DB=MYSQL CORE_RELEASE=3.4 FRAMEWORK_TEST=1
 - DB=MYSQL CORE_RELEASE=3.5
 - DB=MYSQL CORE_RELEASE=3.5 FRAMEWORK_TEST=1

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - "if [ \"$FRAMEWORK_TEST\" = \"\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/cms:$CORE_RELEASE.x-dev; fi"
 - "if [ \"$FRAMEWORK_TEST\" = \"1\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss; fi"
 - cd ~/builds/ss

script:
 - phpunit kapost-bridge/tests/
