language: php 
php: 
 - 5.3

sudo: false

notifications:
  email:
    - devs@webbuildersgroup.com

env:
 - DB=MYSQL CORE_RELEASE=3.1
 - DB=PGSQL CORE_RELEASE=3.1
 - DB=SQLITE3 CORE_RELEASE=3.1
 - DB=MYSQL CORE_RELEASE=3.2
 - DB=PGSQL CORE_RELEASE=3.2
 - DB=SQLITE3 CORE_RELEASE=3.2
 - DB=MYSQL CORE_RELEASE=3.4
 - DB=PGSQL CORE_RELEASE=3.4
 - DB=SQLITE3 CORE_RELEASE=3.4

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script: 
 - phpunit kapost-bridge/tests/
