---
Name: kapostbridge
After:
    - "framework/*"
    - "cms/*"
---
SiteTree:
    extensions:
        - "KapostSiteTreeExtension"
    non_readonly_fields:
        - "URLSegment"
        - "ExtraMeta"
    non_readonly_settings_fields:
        - "CanViewType"
        - "ViewerGroups"
        - "CanEditType"
        - "EditorGroups"
    make_safe_wysiwyg_fields:
        - "Content"


SS_Backtrace:
    ignore_function_args:
        -
            - 'KapostService'
            - 'authenticate'
        -
            - 'PhpXmlRpc\Server'
            - 'parseRequest'
        -
            - 'PhpXmlRpc\Server'
            - 'service'
